import type { Metadata } from "next";
import "./globals.css";

import { ThemeProvider } from "@/providers/Theme-Proider";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "KolkataFF",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <main className="max-w-[1440px] mx-auto px-3">{children}</main>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
