import type { Metadata } from "next";
import "./globals.css";
import PCHeader from "@/components/shared/Header";
import { ThemeProvider } from "@/providers/Theme-Proider";
import MobileHeader from "@/components/shared/MobileHeader";
import Footer from "@/components/shared/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="max-w-7xl mx-auto px-3">
            <PCHeader />
            <MobileHeader />
            {children}
          </div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
